name: Tests

on:
  create: # is used for publishing to PyPI and TestPyPI
    tags: # any tag regardless of its name, no branches
      - "**"
  push: # only publishes pushes to the main branch to TestPyPI
    branches: # any integration branch but not tag
      - "main"
  pull_request:

jobs:
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.8.x]

    steps:
      - uses: actions/checkout@v2 
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Prepare the collection
        id: prepare_collection
        uses: ./.github/actions/ansible_collection
      
      - name: Install test requirements
        run: pip3 install -r test-requirements.txt
   
#       - name: Run pylint
#         run: pylint --verbose -ry plugins
      
      - name: Run black
        run: black -l79 --check .
      
      - name: Run ansible-test sanity
        run: ansible-test sanity --python ${{ matrix.python-version }} --requirements
        working-directory: /usr/share/ansible/collections/ansible_collections/${{ steps.prepare_collection.outputs.collection_namespace }}/${{ steps.prepare_collection.outputs.collection_name }}
#       - uses: actions/checkout@v2
#       - name: Setup Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: ${{ matrix.python }}
       
#       - name: Install ansible-test
#         run: |
#           python -m pip install --upgrade pip
#           pip install ansible-test==1.0.1
#       - name: Perform sanity testing with ansible-test
#         uses: ansible-community/ansible-test-gh-action@release/v1
#         with:
#           ansible-core-version: stable-2.12
#           testing-type: sanity
#           test-deps: >-
#             ansible.netcommon
#             ansible.utils
#       - name: Run Unit test
#         run: |
#           ansible-test units --python 3.6
#       - name: Perform Unit testing with ansible-test
#         uses: rohitthakur2590/ansible-test-gh-action@release/v1
#         with:
#           ansible-core-version: stable-2.12
#           testing-type: units
#           test-deps: >-
#             ansible.netcommon
#             ansible.utils
      - name: Install tox
        run: pip install tox
      - name: Run tox on python version from matrix
        run: tox -e py
